CREATE TABLE IF NOT EXISTS `#__yandex_maps_organizations` (
  `organization_object_id` int(10) unsigned NOT NULL COMMENT 'ID объекта',
  `organization_name` varchar(255) DEFAULT NULL COMMENT 'Название огранизаии',
  `organization_form` varchar(10) DEFAULT NULL COMMENT 'Форма организации: ООО, ЗАО и т.д.',
  `organization_lider_fio` varchar(255) DEFAULT NULL COMMENT 'ФИО руководителя',
  `organization_lider_position` varchar(255) DEFAULT NULL COMMENT 'Должность руководителя',
  `organization_acting_basis` tinyint(1) DEFAULT NULL COMMENT ' Действует на основании',
  `organization_acting_basis_date` int(11) DEFAULT NULL COMMENT 'Дата доверенности',
  `organization_acting_basis_number` varchar(50) DEFAULT NULL COMMENT 'Номер доверенности',
  `organization_type` varchar(50) DEFAULT NULL COMMENT 'Тип организации',
  `organization_trademark` varchar(255) DEFAULT NULL COMMENT 'Торговая марка',
  `organization_contact_fio` varchar(255) DEFAULT NULL COMMENT 'ФИО контактного лица',
  `organization_contact_position` varchar(60) DEFAULT NULL COMMENT 'Должность контактного лица',
  `organization_contact_phone` varchar(50) DEFAULT NULL COMMENT 'Номер телефона контактного лица',
  `organization_address_legal` text COMMENT 'Адрес юридический',
  `organization_address` text COMMENT 'Адрес фактический',
  `organization_phone` varchar(50) DEFAULT NULL COMMENT 'Телефон для справок',
  `organization_email` varchar(50) DEFAULT NULL COMMENT 'Электронный адрес',
  `organization_website` varchar(100) DEFAULT NULL COMMENT 'Вебсайт',
  `organization_image` varchar(50) DEFAULT NULL COMMENT 'Логотип',
  `organization_shedule_24` tinyint(1) DEFAULT '0' COMMENT 'Круглосуточно',
  `organization_shedule_days` varchar(20) DEFAULT NULL COMMENT 'Дни работы',
  `organization_start_in` tinyint(2) DEFAULT NULL COMMENT 'Начало работы в выходные',
  `organization_end_in` tinyint(2) DEFAULT NULL COMMENT 'Конец работы в выходные',
  `organization_service_delivery` tinyint(1) DEFAULT NULL COMMENT 'Услуги по доставке',
  `organization_service_delivery_variants` tinyint(1) DEFAULT NULL COMMENT 'доставка по городу/ доставка по России',
  `organization_license_number` varchar(50) DEFAULT NULL COMMENT 'Номер лицензии',
  `organization_license_date` int(11) DEFAULT NULL COMMENT 'Дата выдачи лицензии',
  `organization_bank_inn` varchar(50) DEFAULT NULL COMMENT 'ИНН банка',
  `organization_bank_kpp` varchar(50) DEFAULT NULL COMMENT 'КПП банка',
  `organization_bank_rs` varchar(50) DEFAULT NULL COMMENT 'Р/С банка',
  `organization_bank_name` varchar(255) DEFAULT NULL COMMENT 'Название банка',
  `organization_bank_ks` varchar(50) DEFAULT NULL COMMENT 'К/С банка',
  `organization_bank_bik` varchar(50) DEFAULT NULL COMMENT 'БИК банка',
  `organization_info` text COMMENT 'Дополнительная информация',
  PRIMARY KEY (`organization_object_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COMMENT='Организации';